### ISSUE TITLE
Create Demo, Improve readme documentation

### ISSUE THREAD

**Issue by arivera12** [arivera12/PdfMakeNet#1]
Replicate what is on pdfmake oficial site play ground into a blazor demo project. 

[PdfMake Playground](http://pdfmake.org/playground.html)

### Tasks

- [x] Basic
- [x] Styles 1
- [x] Styles 2
- [x] Styles 3
- [x] Columns
- [x] Tables
- [x] Lists
- [x] Margin
- [x] Images

**Comment by arivera12** [comment]
@jacobrivera12 The first sample of the pdfmake playground is already replicated.

**Comment by sc231997** [comment]
Hi @arivera12,
I was able to publish the pdfMakeNet [demo site](https://sc231997.github.io/PdfMakeNet/). I have used the Github Pages to make this work. You can find the option for this under the repo's setting.

Currently I have to manually checking-in the release version of the site. But there is way to automate that process using github actions.

**Comment by arivera12** [comment]
Awesome. I need to learn this. I will try take a look today and try with another repo.

**Comment by arivera12** [comment]
For some reason the demo is not working properly pdfmake open a new window with no pdf output.

**Comment by arivera12** [comment]
No error on console also...

**Comment by sc231997** [comment]
Thats weird!
Working fine for me, i am using chrome.

**Comment by arivera12** [comment]
LOL. My add blocker was causing the issue hahaha we need to place a note over this to turn off add blocker when using the demo site. It's working perfectly!

**Comment by sc231997** [comment]
All the demo codes are present in the demo site now.

**Comment by arivera12** [comment]
Keep up the good work man, Thanks very much for contributing on this issue it's was very time consuming for you for sure. Let's see what's next. What do you do for living? I see you are very very good on c# maybe we can work on other types of projects for real customers in a very near future. What you think? Closing this issue.

**Comment by sc231997** [comment]
> Keep up the good work man, Thanks very much for contributing on this issue it's was very time consuming for you for sure. Let's see what's next. 

It was my pleasure. This was my first time when I worked on any open source project. It was great working with you.

>What do you do for living? 

I am a software developer at ADP. What about you?

>I see you are very very good on c# maybe we can work on other types of projects for real customers in a very near future. What you think?

I was going to ask you the same. I really enjoyed working on this. Let me know how can we work together going forward. Let's connect next weekend on `Google Hangout` if that's good with you. Let me know the timing which suits you I will send you the invite.

**Comment by arivera12** [comment]
What kind of chat do you use? I have teams, discord, slack, telegram, whatsapp. Tell me what is the most affordable to send you my user or email.

**Comment by sc231997** [comment]
> What kind of chat do you use? I have teams, discord, slack, telegram, whatsapp. Tell me what is the most affordable to send you my user or email.

Lets connect on discord dn `sc231997`.
