### ISSUE TITLE
Enable use of different fonts

### ISSUE THREAD

**Issue by robertjiles** [arivera12/PdfMakeNet#11]
Hi,

Have made really good use of this so far - now have a need to make use of different fonts within the pdf document.
Is this achievable with the curremt implementation - I noticed docs say default font at the moment? Just want to make sure it's not already been done.

Thanks.

**Comment by sc231997** [comment]
At this moment you can try creating your own custom `vfs_fonts.js` for this you can refer here. https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/shell/
