### ISSUE TITLE
Trim Down Nuget Package Size

### ISSUE THREAD

**Issue by sc231997** [arivera12/PdfMakeNet#3]
As the C# wrapper needs only to generate the JSON of the objects. So can we just have Newtonsoft as its only dependency? So it will be a good idea to remove the other Microsoft.AspNetCore.Mvc related dependency.

I guess @jacobrivera12  has done something similar in his fork repo. Can we have that as a NuGet?

**Comment by arivera12** [comment]
I separate them already but haven't built a new package yet. I made up server side extension helpers in another project. I will try build a new package between today and this weekend.

**Comment by arivera12** [comment]
I was making a fully working demo on blazor but haven't finish it yet since I have been very busy. I have some of those samples locally on my computer but haven't finish them yet.

**Comment by arivera12** [comment]
@sc231997 a new package have been build and uploaded please check the readme.md for more info.

```
Install-Package PdfMakeNet -Version 1.0.5
Install-Package PdfMakeNet.Server.Extensions -Version 1.0.5
```

If you find any bug, issue or feature request open a new issue.

**Comment by sc231997** [comment]
Thank you for such a quick response.

I am really excited about this repo. I would like to contribute to
this project.

Please let me know how to proceed. New to opensource contribution, could u
mentor me if possible.

Thanks,
Chandan Singh

**Comment by arivera12** [comment]
@sc231997 sure I don't have any issues with that. You can fork this project and pull in requests. If you wanna become a direct contributor I think I would need to give you direct access to this repository. I am not sure if everything I know is not done its all the things to be implemented. I started a demo project which is basically copy PdfMake playground site examples and add some mores examples like svg, watermark ,etc. Documentation for developers is not ready also. Few things are not done yet. Tell me when you are available to discuss this and you can start working on the things that are still missing or pending.
